### ISSUE TITLE
Encounter a problem

### ISSUE THREAD

**Issue by qq1176914912** [mihirdilip/Mihir.AspNetCore.Authentication.Basic#17]
Hello, excuse me, now I want to implement a function, that is, when the browser accesses the interface, the pop-up window to enter the account password, if the input error page will display a custom error message.
First of all, you can use a browser pop-up, OnValidateCredentials, to enter your account or password, but if you enter the wrong password, you'll see this:
First of all, I found that your "OnHandleChallenge" method did what I wanted, which is for the page to return custom information:
![image](https://github.com/mihirdilip/aspnetcore-authentication-basic/assets/79817742/ecd4ad0d-5cb0-4d5b-9a2b-803a168ebf23)
I then tried to mimic the OnHandleChallenge method in the "OnValidateCredentials" method, returning an error message when it failed:
![image](https://github.com/mihirdilip/aspnetcore-authentication-basic/assets/79817742/5f56acf6-b511-4ab5-8e73-0a504aa016b4)
After I entered the wrong account password, the effect was not what I thought, he did not return the custom data, but returned the browser error message:
![image](https://github.com/mihirdilip/aspnetcore-authentication-basic/assets/79817742/4c5736ef-0ba5-4fec-a63f-d88100e73e7c)
So I'm trying to use, in combination with the "OnHandleChallenge" and "OnValidateCredentials" methods to get what I want. However, I found that when the two are used together, accessing the interface does not trigger a browser pop-up, but directly returns a custom message for the "OnHandleChallenge" method, so is there a way to combine the effects of the two?

**Comment by mihirdilip** [comment]
Hi @qq1176914912, hope this helps..

```
            OnValidateCredentials = async (context) =>
            {
                // custom code to handle credentials, create principal and call Success method on context.
                var userRepository = context.HttpContext.RequestServices.GetRequiredService<IUserRepository>();
                var user = await userRepository.GetUserByUsername(context.Username);
                var isValid = user != null && user.Password == context.Password;
                if (isValid)
                {
                    context.Response.Headers.Add("ValidationCustomHeader", "From OnValidateCredentials - SUCCESS");
                    var claims = new[]
                    {
                        new Claim("CustomClaimType", "Custom Claim Value - from OnValidateCredentials - SUCCESS")
                    };
                    context.ValidationSucceeded(claims);    // claims are optional
                }
                else
                {
                    context.Response.StatusCode = StatusCodes.Status401Unauthorized;
                    context.Response.Headers.Add("ChallengeCustomHeader", "From OnValidateCredentials - FAILED");
                    await context.Response.WriteAsync("{\"CustomBody\":\"From OnValidateCredentials - FAILED\"}");
                    context.ValidationFailed();
                }
            },

            OnHandleChallenge = async (context) =>
            {
                // custom code to handle authentication challenge unauthorized response.

                if (context.Response.HasStarted) 
                {
                    context.Handled();
                    return;
                }

                context.Response.StatusCode = StatusCodes.Status401Unauthorized;

                context.Response.Headers[HeaderNames.WWWAuthenticate] = $"{BasicDefaults.AuthenticationScheme} realm=\"{context.Options.Realm}\", charset=\"UTF-8\"";

                context.Response.Headers.Add("ChallengeCustomHeader", "From OnHandleChallenge");
                await context.Response.WriteAsync("{\"CustomBody\":\"From OnHandleChallenge\"}");
                context.Handled();
            },

```

**Comment by qq1176914912** [comment]
> Hi @qq1176914912, hope this helps..
> 
> ```
>             OnValidateCredentials = async (context) =>
>             {
>                 // custom code to handle credentials, create principal and call Success method on context.
>                 var userRepository = context.HttpContext.RequestServices.GetRequiredService<IUserRepository>();
>                 var user = await userRepository.GetUserByUsername(context.Username);
>                 var isValid = user != null && user.Password == context.Password;
>                 if (isValid)
>                 {
>                     context.Response.Headers.Add("ValidationCustomHeader", "From OnValidateCredentials - SUCCESS");
>                     var claims = new[]
>                     {
>                         new Claim("CustomClaimType", "Custom Claim Value - from OnValidateCredentials - SUCCESS")
>                     };
>                     context.ValidationSucceeded(claims);    // claims are optional
>                 }
>                 else
>                 {
>                     context.Response.StatusCode = StatusCodes.Status401Unauthorized;
>                     context.Response.Headers.Add("ChallengeCustomHeader", "From OnValidateCredentials - FAILED");
>                     await context.Response.WriteAsync("{\"CustomBody\":\"From OnValidateCredentials - FAILED\"}");
>                     context.ValidationFailed();
>                 }
>             },
> 
>             OnHandleChallenge = async (context) =>
>             {
>                 // custom code to handle authentication challenge unauthorized response.
> 
>                 if (context.Response.HasStarted) 
>                 {
>                     context.Handled();
>                     return;
>                 }
> 
>                 context.Response.StatusCode = StatusCodes.Status401Unauthorized;
> 
>                 context.Response.Headers[HeaderNames.WWWAuthenticate] = $"{BasicDefaults.AuthenticationScheme} realm=\"{context.Options.Realm}\", charset=\"UTF-8\"";
> 
>                 context.Response.Headers.Add("ChallengeCustomHeader", "From OnHandleChallenge");
>                 await context.Response.WriteAsync("{\"CustomBody\":\"From OnHandleChallenge\"}");
>                 context.Handled();
>             },
> ```

Thank you for your help, I found that it meets my requirements.
