### ISSUE TITLE
IgnoreAuthenticationIfAllowAnonymous in HandleAuthenticateAsync specifically doesn't ignore

### ISSUE THREAD

**Issue by ghost** [mihirdilip/Mihir.AspNetCore.Authentication.Basic#9]
### Code in question:
https://github.com/mihirdilip/aspnetcore-authentication-basic/blob/ce690a6c2c349b680de7364fda52b616a0951fc7/src/AspNetCore.Authentication.Basic/BasicHandler.cs#L54-L58

### Problem:
The log statement at line 56 breaks the promise to ignore authentication if the endpoint is annotated with `[AllowAnonymous]`. 

### Expected behavior:
When querying an endpoint annotated with `[AllowAnonymous]`, authentication logic should be ignored.

### Actual behavior:
When querying an endpoint annotated with `[AllowAnonymous]`, two lines of log output are produced, stating that nothing is going on. (logspam)

### Example:
> info: AspNetCore.Authentication.Basic.BasicHandler[0]
>       No 'Authorization' header found in the request.
> info: AspNetCore.Authentication.Basic.BasicHandler[0]
>       No 'Authorization' header found in the request.
> info: AspNetCore.Authentication.Basic.BasicHandler[0]
>       No 'Authorization' header found in the request.
> info: AspNetCore.Authentication.Basic.BasicHandler[0]
>       No 'Authorization' header found in the request.
> info: AspNetCore.Authentication.Basic.BasicHandler[0]
>       No 'Authorization' header found in the request.
> info: AspNetCore.Authentication.Basic.BasicHandler[0]
>       No 'Authorization' header found in the request.
> info: AspNetCore.Authentication.Basic.BasicHandler[0]
>       No 'Authorization' header found in the request.
> info: AspNetCore.Authentication.Basic.BasicHandler[0]
>       No 'Authorization' header found in the request.
> info: AspNetCore.Authentication.Basic.BasicHandler[0]
>       No 'Authorization' header found in the request.
> info: AspNetCore.Authentication.Basic.BasicHandler[0]
>       No 'Authorization' header found in the request.
> info: AspNetCore.Authentication.Basic.BasicHandler[0]
>       No 'Authorization' header found in the request.
> info: AspNetCore.Authentication.Basic.BasicHandler[0]
>       No 'Authorization' header found in the request.
> info: AspNetCore.Authentication.Basic.BasicHandler[0]
>       No 'Authorization' header found in the request.
> info: AspNetCore.Authentication.Basic.BasicHandler[0]
>       No 'Authorization' header found in the request.
> info: AspNetCore.Authentication.Basic.BasicHandler[0]
>       No 'Authorization' header found in the request.
> info: AspNetCore.Authentication.Basic.BasicHandler[0]
>       No 'Authorization' header found in the request.
> info: AspNetCore.Authentication.Basic.BasicHandler[0]
>       No 'Authorization' header found in the request.
> info: AspNetCore.Authentication.Basic.BasicHandler[0]
>       No 'Authorization' header found in the request.
> info: AspNetCore.Authentication.Basic.BasicHandler[0]
>       No 'Authorization' header found in the request.

### Pull request:
#8

**Comment by mihirdilip** [comment]
Hi @hcshmk, your request is updated with 6.0.1 release just published. Sorry it took a while as I was waiting for .net6.0 release and then got busy with other stuff.
